[package]
name = "AdventOfCode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom="7"
itertools="0.10"
pathfinding="4"
hashbrown = "0.13"
ordered-float = "3.4.0"
num-complex = "0.4"
num="0.4"
